name: "AI Code Review Action v2"
description: "Advanced AI-powered code reviews with multiple model support"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  AI_PROVIDER:
    description: "AI provider (openai, anthropic, google)"
    required: true
    default: "openai"
  AI_MODEL:
    description: "AI model to use"
    required: true
    default: "gpt-4"
  AI_API_KEY:
    description: "API key for the chosen AI provider"
    required: true
  REVIEW_BEHAVIOR:
    description: "Review behavior (suggest_approval, comment_only, full_review)"
    required: false
    default: "full_review"
  PROJECT_CONTEXT:
    description: "Additional context about the project"
    required: false
  EXCLUDE_PATTERNS:
    description: "Files to exclude (glob patterns)"
    required: false
    default: "**/*.lock,**/*.json,**/*.md"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "code"
  color: "purple"
